settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: scheggia-cloud-web # unique identifier
    name: scheggia.cloud
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://scheggia.cloud/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: true # should fetch follow redirects, default=false
    linkable: true # allows the title to be a link, default=true

  - id: scheggia-cloud-billing
    name: billing.scheggia.cloud
    url: 'https://billing.scheggia.cloud/'
    method: GET
    expectStatus: 200
    linkable: true
    followRedirect: true

  - id: scheggia-cloud-game
    name: game.scheggia.cloud
    url: 'https://game.scheggia.cloud/'
    method: GET
    expectStatus: 200
    linkable: true
    followRedirect: true
